version: 2.1
orbs:
  react-native: echobind/react-native@0.3.1
workflows:
  version: 2
  main:
    jobs:
      - react-native/node:
          name: node
      - react-native/android:
          name: android
          requires:
            - node
          build:
            - run:
                name: Build
                working_directory: android
                command: |
                  ./gradlew assembleRelease