version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  install:
    docker:
      - image: cimg/node:15.2.1
    steps:
      - checkout
      - run: npm install
  build:
    executor: android/android

    steps:
      - checkout
      - run:
          name: Build
          command: cd android && ./gradlew assembleRelease